### ISSUE TITLE
Unable to get "updatedExisting" flag in  Mongoid.database.command({getlasterror: 1})

### ISSUE THREAD

**Issue by Bhuvan2011** [burgalon/mongoid_optimistic_locking#1]
Hi all,

I am using the latest version of mongoid and trying to implement the database locking using mongoid_optimistic_locking gem.

Follwing is the statement where the problem is encountered
    result =  Mongoid.database.command({getlasterror: 1})

the return value in result is
{"n"=>0, "connectionId"=>949440, "err"=>nil, "ok"=>1.0}

The problem is that the expected return value should be something like this-
 {"n"=>0, "connectionId"=>949440, "err"=>nil, "ok"=>1.0, "updatedExisting"=>true} , but I dont get "updatedExisting" in the return value.

Thanks in advance

PS - I am not sure whether this is the mongoid version problem

**Comment by burgalon** [comment]
It seems like Durran answered you here https://github.com/mongoid/mongoid/issues/1830
It's possible that the gem in not hanlding save of new objects correctly. 
Is that the scenario you are experiencing? 
Which Mongoid version and Mongo DB version are you using?

**Comment by pschuegr** [comment]
I'm experiencing this with mongoid 3.0.4, mongo shell version 2.0.4, and the mongoid3 branch of optimistic_locking.

It seems to be related to this code in the model:

```
has_one :image, :class_name => 'Image', :as => :owner, :validate => false
accepts_nested_attributes_for :image
```

If the first line is

```
has_one :image, :class_name => 'Image', :as => :owner
```

Or the second line is missing, it works.  I don't know enough about mongoid internals to understand whether this is an error or not.  Any thoughts?
