### ISSUE TITLE
any update for mongoid 3 support?

### ISSUE THREAD

**Issue by sandipransing** [burgalon/mongoid_optimistic_locking#11]
gem currently doesn't support for mongoid version 3... is there any updates on same?

**Comment by burgalon** [comment]
As indicated, there's a branch and it's working.
Just add the below to your Gemfile

```
gem 'mongoid_optimistic_locking', git: 'https://github.com/burgalon/mongoid_optimistic_locking', branch: 'mongoid3'
```

**Comment by burgalon** [comment]
So I merged the Mongoid3 branch to master and published a new gem to RubyGems.
Please try including just in your Gemfile

```
gem 'mongoid_optimistic_locking'
```

Make sure you're getting version 0.0.3 and let me know how it works.
